# Generated by Django 4.1.2 on 2022-11-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_did',
            field=models.BooleanField(default=False),
        ),
    ]
